version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/after.sh
      timeout: 300
      runas: root
