version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: Scripts/UnzipResourceBundle.sh
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
      runas: codedeployuser
